import type { Metadata } from "next";
import "@fontsource/inter";
import "./globals.css";
import { ThemeProvider } from "@/components/themes/theme-provider";

export const metadata: Metadata = {
  title: "Bucket Co",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    // <ClerkProvider>
    <html lang="en" suppressHydrationWarning suppressContentEditableWarning>
      <ThemeProvider
        attribute="class"
        defaultTheme="system"
        enableSystem
        disableTransitionOnChange
      >
        <body
          className="inter-400 dark:bg-primarybg bg-white text-primarybg dark:text-white"
          suppressHydrationWarning
        >
          {children}
        </body>
      </ThemeProvider>
    </html>
    // </ClerkProvider>
  );
}
